server:
  port: 8080

spring:
  thymeleaf:
    cache: false

cart:
  service:
    url: http://localhost:8082/cart

catalog:
  service:
    url: http://localhost:8081/api/catalog

customer:
  service:
    url: http://localhost:8082/api/customer